import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "../styles/globals.scss";
import { RouterProvider } from "./providers/RouterProvider";

import styles from "./layout.module.scss";

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} ${styles.module}`}>
        <RouterProvider>
          <header>header</header>
          <div className={styles.content}>{children}</div>
          <footer>footer</footer>
        </RouterProvider>
      </body>
    </html>
  );
}
