name: deployment

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: install dependencies
        run: npm ci

      - name: hello world
        run: echo "Hello, GitHub Actions!"
