name: Storybook test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: install dependencies
        run: npm ci
      - name: install Playwright
        run: npx playwright install --with-deps
      - name: build Storybook
        run: npm run build-storybook --quiet
      - name: serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test-storybook"
